name: file_type_checker
description: "File Signature Matcher written in Dart ~"
publish_to: pub.dev
version: 0.0.1+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
