name: file_type_checker
description: "File Signature Matcher written in Dart ~"
publish_to: https://pub.dev/packages/file_type_matcher
version: 0.0.1+1
repository: https://github.com/Exabyting/file-signature-flutter
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
